development:
  clients:
    default:
      database: my_bank
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

test:
  clients:
    default:
      database: my_bank_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: my_bank
      hosts:
        - localhost:27017

staging:
  clients:
    default:
      database: my_bank
      hosts:
        - localhost:27017
